/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HqRouteImport } from './routes/hq'
import { Route as AppRouteImport } from './routes/app'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as HqIndexRouteImport } from './routes/hq.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSupportRouteImport } from './routes/_site.support'
import { Route as SiteSignupRouteImport } from './routes/_site.signup'
import { Route as SiteServicesRouteImport } from './routes/_site.services'
import { Route as SiteQuoteRouteImport } from './routes/_site.quote'
import { Route as SiteProductsRouteImport } from './routes/_site.products'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as SitePortfolioRouteImport } from './routes/_site.portfolio'
import { Route as SiteLoginRouteImport } from './routes/_site.login'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCareersRouteImport } from './routes/_site.careers'
import { Route as SiteBlogRouteImport } from './routes/_site.blog'
import { Route as HqVaultIndexRouteImport } from './routes/hq.vault.index'
import { Route as HqSupportIndexRouteImport } from './routes/hq.support.index'
import { Route as HqSubscriptionsIndexRouteImport } from './routes/hq.subscriptions.index'
import { Route as HqStaffIndexRouteImport } from './routes/hq.staff.index'
import { Route as HqSmsIndexRouteImport } from './routes/hq.sms.index'
import { Route as HqSecurityIndexRouteImport } from './routes/hq.security.index'
import { Route as HqProjectsIndexRouteImport } from './routes/hq.projects.index'
import { Route as HqProductsIndexRouteImport } from './routes/hq.products.index'
import { Route as HqOfficeIndexRouteImport } from './routes/hq.office.index'
import { Route as HqMarketingIndexRouteImport } from './routes/hq.marketing.index'
import { Route as HqFinanceIndexRouteImport } from './routes/hq.finance.index'
import { Route as HqDeveloperIndexRouteImport } from './routes/hq.developer.index'
import { Route as HqClientsIndexRouteImport } from './routes/hq.clients.index'
import { Route as HqAiIndexRouteImport } from './routes/hq.ai.index'
import { Route as HqClientsIdRouteImport } from './routes/hq.clients.$id'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa.callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRoute = HqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const HqIndexRoute = HqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HqRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSupportRoute = SiteSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSignupRoute = SiteSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SiteQuoteRoute = SiteQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsRoute = SiteProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SitePortfolioRoute = SitePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCareersRoute = SiteCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogRoute = SiteBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SiteRoute,
} as any)
const HqVaultIndexRoute = HqVaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => HqRoute,
} as any)
const HqSupportIndexRoute = HqSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => HqRoute,
} as any)
const HqSubscriptionsIndexRoute = HqSubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => HqRoute,
} as any)
const HqStaffIndexRoute = HqStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => HqRoute,
} as any)
const HqSmsIndexRoute = HqSmsIndexRouteImport.update({
  id: '/sms/',
  path: '/sms/',
  getParentRoute: () => HqRoute,
} as any)
const HqSecurityIndexRoute = HqSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => HqRoute,
} as any)
const HqProjectsIndexRoute = HqProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => HqRoute,
} as any)
const HqProductsIndexRoute = HqProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => HqRoute,
} as any)
const HqOfficeIndexRoute = HqOfficeIndexRouteImport.update({
  id: '/office/',
  path: '/office/',
  getParentRoute: () => HqRoute,
} as any)
const HqMarketingIndexRoute = HqMarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => HqRoute,
} as any)
const HqFinanceIndexRoute = HqFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => HqRoute,
} as any)
const HqDeveloperIndexRoute = HqDeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => HqRoute,
} as any)
const HqClientsIndexRoute = HqClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => HqRoute,
} as any)
const HqAiIndexRoute = HqAiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => HqRoute,
} as any)
const HqClientsIdRoute = HqClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => HqRoute,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRoute
  '/hq': typeof HqRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog': typeof SiteBlogRoute
  '/careers': typeof SiteCareersRoute
  '/contact': typeof SiteContactRoute
  '/login': typeof SiteLoginRoute
  '/portfolio': typeof SitePortfolioRoute
  '/pricing': typeof SitePricingRoute
  '/products': typeof SiteProductsRoute
  '/quote': typeof SiteQuoteRoute
  '/services': typeof SiteServicesRoute
  '/signup': typeof SiteSignupRoute
  '/support': typeof SiteSupportRoute
  '/hq/': typeof HqIndexRoute
  '/hq/clients/$id': typeof HqClientsIdRoute
  '/hq/ai/': typeof HqAiIndexRoute
  '/hq/clients/': typeof HqClientsIndexRoute
  '/hq/developer/': typeof HqDeveloperIndexRoute
  '/hq/finance/': typeof HqFinanceIndexRoute
  '/hq/marketing/': typeof HqMarketingIndexRoute
  '/hq/office/': typeof HqOfficeIndexRoute
  '/hq/products/': typeof HqProductsIndexRoute
  '/hq/projects/': typeof HqProjectsIndexRoute
  '/hq/security/': typeof HqSecurityIndexRoute
  '/hq/sms/': typeof HqSmsIndexRoute
  '/hq/staff/': typeof HqStaffIndexRoute
  '/hq/subscriptions/': typeof HqSubscriptionsIndexRoute
  '/hq/support/': typeof HqSupportIndexRoute
  '/hq/vault/': typeof HqVaultIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog': typeof SiteBlogRoute
  '/careers': typeof SiteCareersRoute
  '/contact': typeof SiteContactRoute
  '/login': typeof SiteLoginRoute
  '/portfolio': typeof SitePortfolioRoute
  '/pricing': typeof SitePricingRoute
  '/products': typeof SiteProductsRoute
  '/quote': typeof SiteQuoteRoute
  '/services': typeof SiteServicesRoute
  '/signup': typeof SiteSignupRoute
  '/support': typeof SiteSupportRoute
  '/': typeof SiteIndexRoute
  '/hq': typeof HqIndexRoute
  '/hq/clients/$id': typeof HqClientsIdRoute
  '/hq/ai': typeof HqAiIndexRoute
  '/hq/clients': typeof HqClientsIndexRoute
  '/hq/developer': typeof HqDeveloperIndexRoute
  '/hq/finance': typeof HqFinanceIndexRoute
  '/hq/marketing': typeof HqMarketingIndexRoute
  '/hq/office': typeof HqOfficeIndexRoute
  '/hq/products': typeof HqProductsIndexRoute
  '/hq/projects': typeof HqProjectsIndexRoute
  '/hq/security': typeof HqSecurityIndexRoute
  '/hq/sms': typeof HqSmsIndexRoute
  '/hq/staff': typeof HqStaffIndexRoute
  '/hq/subscriptions': typeof HqSubscriptionsIndexRoute
  '/hq/support': typeof HqSupportIndexRoute
  '/hq/vault': typeof HqVaultIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRoute
  '/hq': typeof HqRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/blog': typeof SiteBlogRoute
  '/_site/careers': typeof SiteCareersRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/login': typeof SiteLoginRoute
  '/_site/portfolio': typeof SitePortfolioRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/products': typeof SiteProductsRoute
  '/_site/quote': typeof SiteQuoteRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/signup': typeof SiteSignupRoute
  '/_site/support': typeof SiteSupportRoute
  '/_site/': typeof SiteIndexRoute
  '/hq/': typeof HqIndexRoute
  '/hq/clients/$id': typeof HqClientsIdRoute
  '/hq/ai/': typeof HqAiIndexRoute
  '/hq/clients/': typeof HqClientsIndexRoute
  '/hq/developer/': typeof HqDeveloperIndexRoute
  '/hq/finance/': typeof HqFinanceIndexRoute
  '/hq/marketing/': typeof HqMarketingIndexRoute
  '/hq/office/': typeof HqOfficeIndexRoute
  '/hq/products/': typeof HqProductsIndexRoute
  '/hq/projects/': typeof HqProjectsIndexRoute
  '/hq/security/': typeof HqSecurityIndexRoute
  '/hq/sms/': typeof HqSmsIndexRoute
  '/hq/staff/': typeof HqStaffIndexRoute
  '/hq/subscriptions/': typeof HqSubscriptionsIndexRoute
  '/hq/support/': typeof HqSupportIndexRoute
  '/hq/vault/': typeof HqVaultIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/hq'
    | '/sitemap.xml'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/login'
    | '/portfolio'
    | '/pricing'
    | '/products'
    | '/quote'
    | '/services'
    | '/signup'
    | '/support'
    | '/hq/'
    | '/hq/clients/$id'
    | '/hq/ai/'
    | '/hq/clients/'
    | '/hq/developer/'
    | '/hq/finance/'
    | '/hq/marketing/'
    | '/hq/office/'
    | '/hq/products/'
    | '/hq/projects/'
    | '/hq/security/'
    | '/hq/sms/'
    | '/hq/staff/'
    | '/hq/subscriptions/'
    | '/hq/support/'
    | '/hq/vault/'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/sitemap.xml'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/login'
    | '/portfolio'
    | '/pricing'
    | '/products'
    | '/quote'
    | '/services'
    | '/signup'
    | '/support'
    | '/'
    | '/hq'
    | '/hq/clients/$id'
    | '/hq/ai'
    | '/hq/clients'
    | '/hq/developer'
    | '/hq/finance'
    | '/hq/marketing'
    | '/hq/office'
    | '/hq/products'
    | '/hq/projects'
    | '/hq/security'
    | '/hq/sms'
    | '/hq/staff'
    | '/hq/subscriptions'
    | '/hq/support'
    | '/hq/vault'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/_site'
    | '/app'
    | '/hq'
    | '/sitemap.xml'
    | '/_site/blog'
    | '/_site/careers'
    | '/_site/contact'
    | '/_site/login'
    | '/_site/portfolio'
    | '/_site/pricing'
    | '/_site/products'
    | '/_site/quote'
    | '/_site/services'
    | '/_site/signup'
    | '/_site/support'
    | '/_site/'
    | '/hq/'
    | '/hq/clients/$id'
    | '/hq/ai/'
    | '/hq/clients/'
    | '/hq/developer/'
    | '/hq/finance/'
    | '/hq/marketing/'
    | '/hq/office/'
    | '/hq/products/'
    | '/hq/projects/'
    | '/hq/security/'
    | '/hq/sms/'
    | '/hq/staff/'
    | '/hq/subscriptions/'
    | '/hq/support/'
    | '/hq/vault/'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRoute
  HqRoute: typeof HqRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/': {
      id: '/hq/'
      path: '/'
      fullPath: '/hq/'
      preLoaderRoute: typeof HqIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/support': {
      id: '/_site/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SiteSupportRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/signup': {
      id: '/_site/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SiteSignupRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/quote': {
      id: '/_site/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof SiteQuoteRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products': {
      id: '/_site/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SiteProductsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/portfolio': {
      id: '/_site/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof SitePortfolioRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/careers': {
      id: '/_site/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof SiteCareersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog': {
      id: '/_site/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof SiteBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/hq/vault/': {
      id: '/hq/vault/'
      path: '/vault'
      fullPath: '/hq/vault/'
      preLoaderRoute: typeof HqVaultIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/support/': {
      id: '/hq/support/'
      path: '/support'
      fullPath: '/hq/support/'
      preLoaderRoute: typeof HqSupportIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/subscriptions/': {
      id: '/hq/subscriptions/'
      path: '/subscriptions'
      fullPath: '/hq/subscriptions/'
      preLoaderRoute: typeof HqSubscriptionsIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/staff/': {
      id: '/hq/staff/'
      path: '/staff'
      fullPath: '/hq/staff/'
      preLoaderRoute: typeof HqStaffIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/sms/': {
      id: '/hq/sms/'
      path: '/sms'
      fullPath: '/hq/sms/'
      preLoaderRoute: typeof HqSmsIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/security/': {
      id: '/hq/security/'
      path: '/security'
      fullPath: '/hq/security/'
      preLoaderRoute: typeof HqSecurityIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/projects/': {
      id: '/hq/projects/'
      path: '/projects'
      fullPath: '/hq/projects/'
      preLoaderRoute: typeof HqProjectsIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/products/': {
      id: '/hq/products/'
      path: '/products'
      fullPath: '/hq/products/'
      preLoaderRoute: typeof HqProductsIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/office/': {
      id: '/hq/office/'
      path: '/office'
      fullPath: '/hq/office/'
      preLoaderRoute: typeof HqOfficeIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/marketing/': {
      id: '/hq/marketing/'
      path: '/marketing'
      fullPath: '/hq/marketing/'
      preLoaderRoute: typeof HqMarketingIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/finance/': {
      id: '/hq/finance/'
      path: '/finance'
      fullPath: '/hq/finance/'
      preLoaderRoute: typeof HqFinanceIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/developer/': {
      id: '/hq/developer/'
      path: '/developer'
      fullPath: '/hq/developer/'
      preLoaderRoute: typeof HqDeveloperIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/clients/': {
      id: '/hq/clients/'
      path: '/clients'
      fullPath: '/hq/clients/'
      preLoaderRoute: typeof HqClientsIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/ai/': {
      id: '/hq/ai/'
      path: '/ai'
      fullPath: '/hq/ai/'
      preLoaderRoute: typeof HqAiIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/clients/$id': {
      id: '/hq/clients/$id'
      path: '/clients/$id'
      fullPath: '/hq/clients/$id'
      preLoaderRoute: typeof HqClientsIdRouteImport
      parentRoute: typeof HqRoute
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteBlogRoute: typeof SiteBlogRoute
  SiteCareersRoute: typeof SiteCareersRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SitePortfolioRoute: typeof SitePortfolioRoute
  SitePricingRoute: typeof SitePricingRoute
  SiteProductsRoute: typeof SiteProductsRoute
  SiteQuoteRoute: typeof SiteQuoteRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteSignupRoute: typeof SiteSignupRoute
  SiteSupportRoute: typeof SiteSupportRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteBlogRoute: SiteBlogRoute,
  SiteCareersRoute: SiteCareersRoute,
  SiteContactRoute: SiteContactRoute,
  SiteLoginRoute: SiteLoginRoute,
  SitePortfolioRoute: SitePortfolioRoute,
  SitePricingRoute: SitePricingRoute,
  SiteProductsRoute: SiteProductsRoute,
  SiteQuoteRoute: SiteQuoteRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteSignupRoute: SiteSignupRoute,
  SiteSupportRoute: SiteSupportRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface HqRouteChildren {
  HqIndexRoute: typeof HqIndexRoute
  HqClientsIdRoute: typeof HqClientsIdRoute
  HqAiIndexRoute: typeof HqAiIndexRoute
  HqClientsIndexRoute: typeof HqClientsIndexRoute
  HqDeveloperIndexRoute: typeof HqDeveloperIndexRoute
  HqFinanceIndexRoute: typeof HqFinanceIndexRoute
  HqMarketingIndexRoute: typeof HqMarketingIndexRoute
  HqOfficeIndexRoute: typeof HqOfficeIndexRoute
  HqProductsIndexRoute: typeof HqProductsIndexRoute
  HqProjectsIndexRoute: typeof HqProjectsIndexRoute
  HqSecurityIndexRoute: typeof HqSecurityIndexRoute
  HqSmsIndexRoute: typeof HqSmsIndexRoute
  HqStaffIndexRoute: typeof HqStaffIndexRoute
  HqSubscriptionsIndexRoute: typeof HqSubscriptionsIndexRoute
  HqSupportIndexRoute: typeof HqSupportIndexRoute
  HqVaultIndexRoute: typeof HqVaultIndexRoute
}

const HqRouteChildren: HqRouteChildren = {
  HqIndexRoute: HqIndexRoute,
  HqClientsIdRoute: HqClientsIdRoute,
  HqAiIndexRoute: HqAiIndexRoute,
  HqClientsIndexRoute: HqClientsIndexRoute,
  HqDeveloperIndexRoute: HqDeveloperIndexRoute,
  HqFinanceIndexRoute: HqFinanceIndexRoute,
  HqMarketingIndexRoute: HqMarketingIndexRoute,
  HqOfficeIndexRoute: HqOfficeIndexRoute,
  HqProductsIndexRoute: HqProductsIndexRoute,
  HqProjectsIndexRoute: HqProjectsIndexRoute,
  HqSecurityIndexRoute: HqSecurityIndexRoute,
  HqSmsIndexRoute: HqSmsIndexRoute,
  HqStaffIndexRoute: HqStaffIndexRoute,
  HqSubscriptionsIndexRoute: HqSubscriptionsIndexRoute,
  HqSupportIndexRoute: HqSupportIndexRoute,
  HqVaultIndexRoute: HqVaultIndexRoute,
}

const HqRouteWithChildren = HqRoute._addFileChildren(HqRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRoute,
  HqRoute: HqRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
